CREATE TABLE [dbo].[EsquemaOrganiza] (
    [PK]                           NVARCHAR (400) NULL,
    [IdEsquemaData]                INT            NOT NULL,
    [IdEsquemaVista]               INT            NOT NULL,
    [VistaFK]                      NVARCHAR (400) NULL,
    [VistaPK]                      NVARCHAR (400) NULL,
    [DataEsquemaJson]              NVARCHAR (MAX) NULL,
    [IdEsquema]                    INT            NOT NULL,
    [ONAIdONA]                     INT            NOT NULL,
    [ONAPais]                      NVARCHAR (40)  NULL,
    [ONAUrlIcono]                  NVARCHAR (400) NULL,
    [ONASiglas]                    NVARCHAR (40)  NULL,
    [OrgNombreComercial]           NVARCHAR (400) NULL,
    [OrgRazonSocial]               NVARCHAR (400) NULL,
    [OrgPais]                      NVARCHAR (400) NULL,
    [OrgCiudad]                    NVARCHAR (400) NULL,
    [OrgDireccion]                 NVARCHAR (400) NULL,
    [OrgTelefono]                  NVARCHAR (400) NULL,
    [OrgWeb]                       NVARCHAR (900) NULL,
    [OrgCorreo]                    NVARCHAR (400) NULL,
    [OrgEstadoAcreditado]          NVARCHAR (400) NULL,
    [OrgEsquemaAcreditado]         NVARCHAR (400) NULL,
    [OrgNormaAcreditada]           NVARCHAR (400) NULL,
    [OrgReconocimiento]            NVARCHAR (400) NULL,
    [OrgFechaEfectivaAcreditacion] NVARCHAR (400) NULL,
    [OrgPeriodoVigencia]           NVARCHAR (400) NULL,
    [OrgFechaActualizacion]        NVARCHAR (400) NULL,
    [OrgCodigoAcreditacion]        NVARCHAR (400) NULL,
    [OrgUrlCertificado]            NVARCHAR (400) NULL,
    [DataFecha]                    DATETIME       DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_EO_IdEsquemaData] PRIMARY KEY CLUSTERED ([IdEsquemaData] ASC),
    CONSTRAINT [FK_EO_IdEsquemaVista] FOREIGN KEY ([IdEsquemaVista]) REFERENCES [dbo].[EsquemaVista] ([IdEsquemaVista])
);

