version: "3.2"
services:
  sqlserver:
    container_name: sqlserver
    build:
      dockerfile: sqlserver-fulltext.ubuntu.Dockerfile
    image: aruponse/sqlserver-fts:0.0.2
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "pat_mic_DBKEY"
      ACCEPT_EULA: "Y"